#!/bin/bash

for DIR in Aciculoconidium__aculeatum__34654 Alloascoidea__hylecoeti Ambrosiozyma__ambrosiae__26137 Ambrosiozyma__kashinagacola Ambrosiozyma__maleeae__35040 Ambrosiozyma__monospora Ambrosiozyma__oregonensis__34946 Ambrosiozyma__philentoma__34947 Ambrosiozyma__pseudovanderkliftii__35041 Ambrosiozyma__vanderkliftii__26145 Arxula__adeninivorans Ascoidea__asiatica Ascoidea__rubescens Ashbya__aceri Babjeviella__inositovora Barnettozyma__californica__35044 Barnettozyma__hawaiiensis__35045 Barnettozyma__populi__35046 Barnettozyma__pratensis__35047 Barnettozyma__salicaria__35048 Blastobotrys__americana__34681 Blastobotrys__mokoenaii__34675 Blastobotrys__muscicola__34674 Blastobotrys__nivea__34673 Blastobotrys__peoriensis__34671 Blastobotrys__proliferans__34670 Blastobotrys__raffinofermentans__34669 Blastobotrys__serpentis__34667 Botryozyma__nematodophila__34655 Brettanomyces__anomalus Brettanomyces__custersianus__26197 Candida__albicans Candida__apicola Candida__arabinofermentans Candida__ascalaphidarum__41855 Candida__athensensis__34632 Candida__auris Candida__azyma__35286 Candida__blattae__35335 Candida__boidinii__JCM9604 Candida__canberraensis__35018 Candida__carpophila Candida__corydali__34990 Candida__cretensis__35033 Candida__dubliniensis Candida__emberorum__35022 Candida__fragi__35302 Candida__freyschussii__34967 Candida__fructus__34988 Candida__gatunensis__35032 Candida__glabrata Candida__golubevii__41862 Candida__gorgasii__41863 Candida__gotoi__35681 Candida__hawaiiana__41743 Candida__heveicola__35707 Candida__hispaniensis__35633 Candida__homilentoma Candida__incommunis__35244 Candida__infanticola Candida__intermedia Candida__kruisii__35031 Candida__montana__35037 Candida__mycetangii__35689 Candida__orba__35673 Candida__oregonensis__34986 Candida__orthopsilosis Candida__parapsilosis Candida__ponderosae__35261 Candida__pyralidae__35011 Candida__restingae__34648 Candida__rhagii__35679 Candida__salmanticensis__35691 Candida__schatavii__34643 Candida__sojae Candida__sorboxylosa Candida__stellimalicola__34597 Candida__succiphila Candida__tammaniensis__41833 Candida__tanzawaensis Candida__tenuis Candida__tropicalis Candida__vartiovaarae__35690 Candida__versatilis Candida__wancherniae__41840 Cephaloascus__albidus__34998 Cephaloascus__fragrans__34999 Citeromyces__hawaiiensis__34950 Citeromyces__matritensis__26142 Citeromyces__siamensis__34952 Clavispora__lusitaniae Cyberlindnera__americana__35703 Cyberlindnera__fabianii__JCM3601 Cyberlindnera__jadinii Cyberlindnera__maclurae__35699 Cyberlindnera__misumaiensis__34979 Cyberlindnera__mrakii__34978 Cyberlindnera__petersonii__35325 Cyberlindnera__saturnus__35686 Cyberlindnera__suaveolens__35687 Cyberlindnera__xylosilytica__35688 Danielozyma__ontarioensis__34973 Deakozyma__indianensis__34974 Debaryomyces__fabryi__41829 Debaryomyces__hansenii Debaryomyces__maramus__41713 Debaryomyces__nepalensis__41693 Debaryomyces__prosopidis__41678 Debaryomyces__subglobosus__41824 Dekkera__bruxellensis Diddensiella__caesifluorescens__34660 Dipodascus__albidus__34661 Dipodascus__geniculatus__41822 Eremothecium__coryli Eremothecium__cymbalariae Eremothecium__gossypii Eremothecium__sinecaudum Geotrichum__candidum Hanseniaspora__clermontiae__34963 Hanseniaspora__osmophila__34957 Hanseniaspora__pseudoguilliermondii__35695 Hanseniaspora__singularis__35696 Hanseniaspora__uvarum Hanseniaspora__valbyensis Hanseniaspora__vinae Hyphopichia__burtonii Hyphopichia__heimii__35318 Kazachstania__aerobia__yHAB164 Kazachstania__africana Kazachstania__bromeliacearum__yHAB136 Kazachstania__humatica__yHAB140 Kazachstania__intestinalis__yHAB148 Kazachstania__kunashirensis__yHAB160 Kazachstania__martiniae__yHAB132 Kazachstania__naganishii Kazachstania__rosinii__yHAB153 Kazachstania__siamensis__yHAB143 Kazachstania__solicola__yHAB159 Kazachstania__spencerorum__yHAB155 Kazachstania__taianensis__yHAB147 Kazachstania__transvaalensis__yHAB154 Kazachstania__turicensis__yHAB134 Kazachstania__unispora__yHAB133 Kazachstania__viticola__yHAB158 Kazachstania__yakushimaensis__yHAB166 Kloeckera__hatyaiensis__35684 Kluyveromyces__aestuarii__34709 Kluyveromyces__dobzhanskii__34710 Kluyveromyces__lactis Kluyveromyces__marxianus Kodamaea__laetipori__34665 Kodamaea__ohmeri__35677 Komagataella__pastoris Komagataella__populi__26274 Komagataella__pseudopastoris__34939 Kregervanrija__delftensis__35674 Kregervanrija__fluxuum__35675 Kuraishia__capsulata Kuraishia__molischiana__34933 Kuraishia__ogatae__34932 Kurtzmaniella__cleridarum__35667 Lachancea__cidri Lachancea__dasiensis Lachancea__fantastica Lachancea__fermentati Lachancea__kluyveri Lachancea__lanzarotensis Lachancea__meyersii Lachancea__mirantina Lachancea__nothofagi Lachancea__quebecensis Lachancea__thermotolerans Lachancea__waltii Lipomyces__arxii__34754 Lipomyces__doorenjongii__34757 Lipomyces__japonicus__34758 Lipomyces__kononenkoae__34760 Lipomyces__lipofer__34761 Lipomyces__mesembrius__34749 Lipomyces__oligophaga__34748 Lipomyces__starkeyi Lipomyces__suomiensis__34742 Lodderomyces__elongisporus Magnusiomyces__tetrasperma__41818 Martiniozyma__abiesophila__34631 Metschnikowia__aberdeeniae Metschnikowia__arizonensis Metschnikowia__bicuspidata Metschnikowia__borealis Metschnikowia__bowlesiae Metschnikowia__cerradonensis Metschnikowia__continentalis Metschnikowia__dekortum Metschnikowia__drakensbergensis Metschnikowia__hamakuensis Metschnikowia__hawaiiensis Metschnikowia__hibisci Metschnikowia__ipomoeae Metschnikowia__kamakouana Metschnikowia__kipukae Metschnikowia__lockheadii  Metschnikowia__matae__maris Metschnikowia__mauinuiana Metschnikowia__proteae Metschnikowia__santaceciliae Metschnikowia__shivogae Metschnikowia__similis Meyerozyma__caribbica__35662 Meyerozyma__guilliermondii Middelhovenomyces__tepae__35665 Millerozyma__acaciae Nadsonia__fulvescens__34635 Nadsonia__fulvescens_var_elongata Nakaseomyces__bacillisporus Nakaseomyces__bracarensis Nakaseomyces__castellii Nakaseomyces__delphensis Nakaseomyces__nivariensis Nakazawaea__holstii__34918 Nakazawaea__peltata Naumovozyma__castellii Naumovozyma__dairenensis Ogataea__glucozyma__34897 Ogataea__henricii__26124 Ogataea__kodamae__34899 Ogataea__methanolica Ogataea__methylivora__34901 Ogataea__minuta__34902 Ogataea__naganishii__34903 Ogataea__nitratoaversa__34636 Ogataea__nonfermentans__34904 Ogataea__parapolymorpha Ogataea__philodendra__34893 Ogataea__pilisensis__34892 Ogataea__pini__34891 Ogataea__polymorpha Ogataea__populiabae__34637 Ogataea__ramenticola__34890 Ogataea__trehaloabstinens__34887 Ogataea__trehalophila__34886 Ogataea__zsoltii__34885 Pachysolen__tannophilus Peterozyma__toletana__34884 Peterozyma__xylosa__34883 Phaffomyces__antillensis__35671 Phaffomyces__opuntiae__35670 Phaffomyces__thermotolerans__35672 Pichia__exigua__34629 Pichia__heedii__34627 Pichia__kudriavzevii__34625 Pichia__membranifaciens Pichia__nakasei__34624 Pichia__norvegensis__34623 Pichia__occidentalis__34622 Pichia__terricola__35301 Priceomyces__carsonii__35296 Priceomyces__castillae__35297 Priceomyces__haplophilus Priceomyces__medius__34606 Saccharomyces__arboricola Saccharomyces__cerevisiae Saccharomyces__eubayanus Saccharomyces__kudriavzevii Saccharomyces__mikatae Saccharomyces__paradoxus Saccharomyces__uvarum Saccharomycopsis__capsularis__34607 Saccharomycopsis__malanga Saprochaete__clavata Saturnispora__dispora__35659 Saturnispora__hagleri__34610 Saturnispora__mendoncae__34611 Saturnispora__saitoi__34612 Saturnispora__serradocipensis__34613 Saturnispora__silvae__34614 Saturnispora__zaruensis__34615 Scheffersomyces__lignosus Scheffersomyces__stipitis Spathaspora__arborariae Spathaspora__girioi Spathaspora__gorwiae Spathaspora__hagerdaliae Spathaspora__passalidarum Spencermartinsiella__europaea__34605 Sporopachydermia__lactativora__34604 Sporopachydermia__quercuum Starmera__amethionina__35658 Starmera__quercuum__34594 Starmerella__bombicola__JCM9596 Sugiyamaella__lignohabitans Tetrapisispora__blattae Tetrapisispora__fleetii__34875 Tetrapisispora__iriomotensis__34876 Tetrapisispora__namnaonensis__34877 Tetrapisispora__phaffii Tortispora__caseinolytica Tortispora__ganteri__35654 Tortispora__starmeri__35279 Torulaspora__delbrueckii Torulaspora__franciscae__26152 Torulaspora__maleeae__35652 Torulaspora__microellipsoides__35651 Torulaspora__pretoriensis__34881 Trigonopsis__variabilis__35650 Trigonopsis__vinaria__35282 Vanderwaltozyma__polyspora Wickerhamia__fluorescens Wickerhamiella__cacticola__34646 Wickerhamiella__domercqiae Wickerhamomyces__alni__35274 Wickerhamomyces__anomalus Wickerhamomyces__bovis__35271 Wickerhamomyces__canadensis__35639 Wickerhamomyces__ciferrii Wickerhamomyces__hampshirensis__35268 Yamadazyma__nakazawae__35252 Yamadazyma__philogaea__35640 Yamadazyma__scolyti__35641 Yarrowia__bubula__35643 Yarrowia__deformans Yarrowia__divulgata__35645 Yarrowia__keelungensis Yarrowia__lipolytica Yueomyces__sinensis__35629 Zygoascus__meyerae__35243 Zygoascus__ofunaensis__35242 Zygosaccharomyces__bailii Zygosaccharomyces__bisporus__34866 Zygosaccharomyces__kombuchaensis__34865 Zygosaccharomyces__rouxii Zygotorulaspora__florentina__34862 Zygotorulaspora__mrakii__26256 
   #Metschnikowia__matae - have to do this one by hand! 

   do

#pulling out sequences corresponding to correct species (DIR)
SPP="$(echo $DIR | sed -e 's/__/_/g')"

grep $SPP xyl1_subgroup.fasta > file.txt

#fixing sequence names in DIR.cds.fasta 

sed -e 's/ /_/g' $DIR\/$DIR\.cds.fasta > fixed1.fasta

sed -e 's/-/_/g' fixed1.fasta > fixed2.fasta

sed -e 's/+/_/g' fixed2.fasta > fixed3.fasta

sed -e 's/|/_/g' fixed3.fasta > fixed4.fasta

sed -e 's/:/_/g' fixed4.fasta > fixed5.fasta

sed -e 's/__/_/g' fixed5.fasta > corrected_$DIR\.cds.fasta

rm fixed*

awk '/>/{sub(">","&"FILENAME"_");sub(/\.cds.fasta/,x)}1' corrected_$DIR\.cds.fasta > adjusted_corrected_$DIR\.cds.fasta

#index the file 
/opt/bifxapps/samtools/samtools faidx adjusted_corrected_$DIR\.cds.fasta

 cat file.txt | while read line 
    do
#for each line in subgroup file

ORF="$(echo $line | sed -n -e 's/^.*ORF//p')"

SEQ="$(grep "$ORF" adjusted_corrected_$DIR\.cds.fasta)"

SEQ1="$(echo "$SEQ" | sed 's/>//g')"

/opt/bifxapps/samtools/samtools faidx adjusted_corrected_$DIR\.cds.fasta $SEQ1 > $SEQ1\.fna

done

done

rm *.fai

cat *.fna > xyl1_subgroup-cds.fasta

rm *.fna

rm *corrected*
